USE School;
GO



CREATE TABLE Classes
(
    Class_ID BIGINT NOT NULL IDENTITY,
    School_Year DATE NOT NULL,
    Class_Code VARCHAR(30),
    Class_Name VARCHAR(50)
)
GO

ALTER TABLE Classes ADD CONSTRAINT Classes_PK PRIMARY KEY NONCLUSTERED (Class_ID)
WITH (
    ALLOW_PAGE_LOCKS = ON,
    ALLOW_ROW_LOCKS = ON
)
GO

CREATE TABLE Competitions
(
    Competition_ID BIGINT NOT NULL IDENTITY,
    Competition_Name VARCHAR(50)
)
GO

ALTER TABLE Competitions ADD CONSTRAINT Competitions_PK PRIMARY KEY CLUSTERED (Competition_ID)
WITH (
    ALLOW_PAGE_LOCKS = ON,
    ALLOW_ROW_LOCKS = ON
)
GO

CREATE TABLE Competition_Students
(
    Result VARCHAR(100) NOT NULL,
    Competition_ID BIGINT NOT NULL,
    Student_ID BIGINT NOT NULL
)
GO

CREATE TABLE Grades
(
    Grade_ID BIGINT NOT NULL IDENTITY,
    Grade FLOAT NOT NULL,
    Comment VARCHAR(255),
    Grade_Date DATE,
    Attendance_ID NUMERIC(28) NOT NULL
)
GO

ALTER TABLE Grades ADD CONSTRAINT Grades_PK PRIMARY KEY NONCLUSTERED (Grade_ID)
WITH (
    ALLOW_PAGE_LOCKS = ON,
    ALLOW_ROW_LOCKS = ON
)
GO

CREATE TABLE People
(
    Person_ID BIGINT NOT NULL,
    First_Name VARCHAR(50) NOT NULL,
    Last_Name VARCHAR(50) NOT NULL,
    Gender VARCHAR(50) NOT NULL,
    Birth_Date DATE NOT NULL,
    Email VARCHAR(50) NOT NULL UNIQUE CLUSTERED
)
GO

ALTER TABLE People ADD CONSTRAINT People_PK PRIMARY KEY NONCLUSTERED (Person_ID)
WITH (
    ALLOW_PAGE_LOCKS = ON,
    ALLOW_ROW_LOCKS = ON
)
GO

CREATE TABLE Employees
(
    Salary BIGINT,
    Employment_Type BIGINT,
    Phone_Number VARCHAR(15),
    Person_ID BIGINT NOT NULL,
    Position_ID NUMERIC(28) NOT NULL
)
GO

ALTER TABLE Employees ADD CONSTRAINT Employees_PK PRIMARY KEY NONCLUSTERED (Person_ID)
WITH (
    ALLOW_PAGE_LOCKS = ON,
    ALLOW_ROW_LOCKS = ON
)
GO

CREATE TABLE Subjects
(
    Subject_Name VARCHAR(50) NOT NULL
)
GO

ALTER TABLE Subjects ADD CONSTRAINT Subjects_PK PRIMARY KEY NONCLUSTERED (Subject_Name)
WITH (
    ALLOW_PAGE_LOCKS = ON,
    ALLOW_ROW_LOCKS = ON
)
GO

CREATE TABLE Positions
(
    Position_Name VARCHAR(50) NOT NULL,
    Position_ID NUMERIC(28) NOT NULL IDENTITY NOT FOR REPLICATION
)
GO

ALTER TABLE Positions ADD CONSTRAINT Positions_PK PRIMARY KEY NONCLUSTERED (Position_ID)
WITH (
    ALLOW_PAGE_LOCKS = ON,
    ALLOW_ROW_LOCKS = ON
)
GO

CREATE TABLE Student_Classes
(
    Student_ID BIGINT NOT NULL,
    Class_ID BIGINT NOT NULL,
    Start_Date DATE,
    End_Date DATE
)
GO

ALTER TABLE Student_Classes ADD CONSTRAINT Student_Classes_PK PRIMARY KEY NONCLUSTERED (Class_ID, Student_ID)
WITH (
    ALLOW_PAGE_LOCKS = ON,
    ALLOW_ROW_LOCKS = ON
)
GO

CREATE TABLE Attendance
(
    Student_ID BIGINT NOT NULL,
    Lesson_ID BIGINT NOT NULL,
    Present BIT NOT NULL,
    Notes CHAR(400),
    Attendance_ID NUMERIC(28) NOT NULL IDENTITY NOT FOR REPLICATION
)
GO

ALTER TABLE Attendance ADD CONSTRAINT Attendance_PK PRIMARY KEY NONCLUSTERED (Attendance_ID)
WITH (
    ALLOW_PAGE_LOCKS = ON,
    ALLOW_ROW_LOCKS = ON
)
GO

CREATE TABLE Students
(
    Guardian_Phone_Number VARCHAR(15) NOT NULL,
    Person_ID BIGINT NOT NULL
)
GO

ALTER TABLE Students ADD CONSTRAINT Students_PK PRIMARY KEY NONCLUSTERED (Person_ID)
WITH (
    ALLOW_PAGE_LOCKS = ON,
    ALLOW_ROW_LOCKS = ON
)
GO

CREATE TABLE Lessons
(
    Lesson_ID BIGINT NOT NULL IDENTITY,
    Room_Number BIGINT,
    Subject_Name VARCHAR(50) NOT NULL,
    Lesson_DateTime DATETIME,
    Class_ID BIGINT NOT NULL,
    Employee_ID BIGINT NOT NULL
)
GO

ALTER TABLE Lessons ADD CONSTRAINT Lessons_PK PRIMARY KEY NONCLUSTERED (Lesson_ID)
WITH (
    ALLOW_PAGE_LOCKS = ON,
    ALLOW_ROW_LOCKS = ON
)
GO

ALTER TABLE Competition_Students
ADD CONSTRAINT Competition_Students_Competitions_FK FOREIGN KEY (Competition_ID)
REFERENCES Competitions (Competition_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
GO

ALTER TABLE Competition_Students
ADD CONSTRAINT Competition_Students_Students_FK FOREIGN KEY (Student_ID)
REFERENCES Students (Person_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
GO

ALTER TABLE Grades
ADD CONSTRAINT Grades_Attendance_FK FOREIGN KEY (Attendance_ID)
REFERENCES Attendance (Attendance_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
GO

ALTER TABLE Employees
ADD CONSTRAINT Employees_People_FK FOREIGN KEY (Person_ID)
REFERENCES People (Person_ID)
ON DELETE CASCADE
ON UPDATE NO ACTION
GO

ALTER TABLE Employees
ADD CONSTRAINT Employees_Positions_FK FOREIGN KEY (Position_ID)
REFERENCES Positions (Position_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
GO

ALTER TABLE Student_Classes
ADD CONSTRAINT Student_Classes_Classes_FK FOREIGN KEY (Class_ID)
REFERENCES Classes (Class_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
GO

ALTER TABLE Student_Classes
ADD CONSTRAINT Student_Classes_Students_FK FOREIGN KEY (Student_ID)
REFERENCES Students (Person_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
GO

ALTER TABLE Attendance
ADD CONSTRAINT Attendance_Students_FK FOREIGN KEY (Student_ID)
REFERENCES Students (Person_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
GO

ALTER TABLE Attendance
ADD CONSTRAINT Attendance_Lessons_FK FOREIGN KEY (Lesson_ID)
REFERENCES Lessons (Lesson_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
GO

ALTER TABLE Students
ADD CONSTRAINT Students_People_FK FOREIGN KEY (Person_ID)
REFERENCES People (Person_ID)
ON DELETE CASCADE
ON UPDATE NO ACTION
GO

ALTER TABLE Lessons
ADD CONSTRAINT Lessons_Classes_FK FOREIGN KEY (Class_ID)
REFERENCES Classes (Class_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
GO

ALTER TABLE Lessons
ADD CONSTRAINT Lessons_Employees_FK FOREIGN KEY (Employee_ID)
REFERENCES Employees (Person_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
GO

ALTER TABLE Lessons
ADD CONSTRAINT Lessons_Subjects_FK FOREIGN KEY (Subject_Name)
REFERENCES Subjects (Subject_Name)
ON DELETE NO ACTION
ON UPDATE NO ACTION
GO